### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Plackys** [kaytea42/Pizza-Tower-Demo-1-Engine#4]
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at GMAssetCompiler.TexturePage.LoadTPECacheFile(String _cacheFile)
   at GMAssetCompiler.TexturePage.AddImage(String _filename, Boolean _htile, Boolean _vtile, Boolean _pack, Boolean _seperateTexturePage, Boolean _ignoreTextureScale, Int32 _nFrame, String _groupName, String _resourceName, String[] _cacheFiles)
   at GMAssetCompiler.WADSaver`1.<>c.<WriteSprites>b__111_0(KeyValuePair`2 _kvp)
   at GMAssetCompiler.Program.<>c__DisplayClass600_0`2.<ParallelExec>b__0(Object oo)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
elapsed time 00:00:12.7175201s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.6.0.137/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\*******\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 07/19/2023 18:28:48
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

**Comment by DrEngineer1** [comment]
it sounds like its a cpu issue. the mention of system threading is obvious enough i think.

**Comment by Plackys** [comment]
> it sounds like its a cpu issue. the mention of system threading is obvious enough i think.

i already fixed it by reinstalling gamemaker
